#!/usr/bin/env python3
"""
Automated Test and Documentation Generator for https_wrapper.py
Spins up the SecureMCPHTTPSServer, probes all endpoints, and generates a markdown documentation file.
"""

import json
import logging
import time
import requests
import urllib3
from pathlib import Path

# Suppress insecure request warnings for our self-signed certs during testing
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Import the server
from https_wrapper import SecureMCPHTTPSServer

def generate_markdown(doc_file: Path, results: dict):
    """Write the test results to a markdown documentation file."""
    doc_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(doc_file, "w") as f:
        f.write("# Sovereign MCP HTTPS Wrapper - Endpoint Documentation\n\n")
        f.write("This document is auto-generated by `test_https_wrapper.py` and contains real payloads from the running server.\n\n")
        
        f.write("## Overview\n")
        f.write("The `https_wrapper.py` provides a secure, TLS-encrypted HTTP layer for the MCP Server. ")
        f.write("It uses Bearer token authentication (API Key) and implements rate limiting.\n\n")
        
        f.write("## Authentication\n")
        f.write("Pass the API key in the `Authorization` header:\n")
        f.write("```http\nAuthorization: Bearer <YOUR_API_KEY>\n```\n")
        f.write("Alternatively, use the query parameter `?api_key=<YOUR_API_KEY>`.\n\n")
        
        f.write("## Endpoints\n\n")
        
        for endpoint, data in results.items():
            f.write(f"### `{data['method']} {endpoint}`\n")
            f.write(f"**Status Code**: `{data['status']}`\n\n")
            if data.get("description"):
                f.write(f"{data['description']}\n\n")
            
            f.write("**Response Headers (Partial):**\n")
            f.write("```http\n")
            for h, v in data.get("headers", {}).items():
                if h.lower() in ["content-type", "x-ratelimit-limit", "x-ratelimit-remaining", "access-control-allow-origin"]:
                    f.write(f"{h}: {v}\n")
            f.write("```\n\n")
            
            f.write("**Response Body:**\n")
            if data['is_json']:
                f.write("```json\n")
                f.write(json.dumps(data['body'], indent=2))
                f.write("\n```\n\n")
            else:
                f.write("```text\n")
                f.write(str(data['body']))
                f.write("\n```\n\n")

def run_tests():
    logging.basicConfig(level=logging.INFO)
    
    # Random port for testing
    port = 8444
    host = "localhost"
    
    print(f"Starting test server on {host}:{port}...")
    server = SecureMCPHTTPSServer(host=host, port=port, debug=False, allow_external=True)
    
    if not server.start_server():
        print("Failed to start server for testing.")
        return
        
    api_key = server.get_api_key()
    base_url = f"https://{host}:{port}"
    
    headers = {
        "Authorization": f"Bearer {api_key}"
    }
    
    print(f"Server started. API Key: {api_key}")
    # Wait for the server to fully initialize
    time.sleep(2)
    
    results = {}
    
    try:
        # 1. GET / (Server Info)
        print("Testing GET /")
        res = requests.get(f"{base_url}/", headers=headers, verify=False)
        results["/"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": "application/json" in res.headers.get("Content-Type", ""),
            "body": res.json() if "application/json" in res.headers.get("Content-Type", "") else res.text,
            "description": "Returns general server information and status."
        }
        
        # 2. GET /health
        print("Testing GET /health")
        res = requests.get(f"{base_url}/health", headers=headers, verify=False)
        results["/health"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Health check endpoint for load balancers and orchestrators."
        }
        
        # 3. GET /tools
        print("Testing GET /tools")
        res = requests.get(f"{base_url}/tools", headers=headers, verify=False)
        results["/tools"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Lists all available MCP tools on the server."
        }
        
        # 4. GET /metrics
        print("Testing GET /metrics")
        res = requests.get(f"{base_url}/metrics", headers=headers, verify=False)
        results["/metrics"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Performance and security metrics."
        }
        
        # 5. GET /api-info
        print("Testing GET /api-info")
        res = requests.get(f"{base_url}/api-info", headers=headers, verify=False)
        results["/api-info"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Internal API documentation overview."
        }
        
        # 6. GET /openapi.json
        print("Testing GET /openapi.json")
        res = requests.get(f"{base_url}/openapi.json", headers=headers, verify=False)
        results["/openapi.json"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Dynamic OpenAPI 3.1 schema generated from the active tool catalog. Used for ChatGPT Actions integration."
        }
        
        # 7. GET /.well-known/ai-plugin.json
        print("Testing GET /.well-known/ai-plugin.json")
        res = requests.get(f"{base_url}/.well-known/ai-plugin.json", headers=headers, verify=False)
        results["/.well-known/ai-plugin.json"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "ChatGPT Plugin Manifest."
        }
        
        # 8. GET /claude-config
        print("Testing GET /claude-config")
        res = requests.get(f"{base_url}/claude-config", headers=headers, verify=False)
        results["/claude-config"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Claude Desktop `mcpServers` configuration JSON snippet."
        }
        
        # 9. GET /webhooks
        print("Testing GET /webhooks")
        res = requests.get(f"{base_url}/webhooks", headers=headers, verify=False)
        results["/webhooks"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "List currently registered webhooks."
        }
        
        # 10. POST /mcp (JSON-RPC)
        print("Testing POST /mcp")
        mcp_payload = {
            "jsonrpc": "2.0",
            "id": "test-id-1",
            "method": "tools/list",
            "params": {}
        }
        res = requests.post(f"{base_url}/mcp", headers=headers, json=mcp_payload, verify=False)
        results["/mcp"] = {
            "method": "POST",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": True,
            "body": res.json(),
            "description": "Standard MCP JSON-RPC protocol endpoint."
        }
        
        # 11. GET /mcp (SSE Stream)
        print("Testing GET /mcp (SSE Stream Headers)")
        sse_headers = headers.copy()
        sse_headers["Accept"] = "text/event-stream"
        # Only request stream, read headers, close immediately to not hang
        res = requests.get(f"{base_url}/mcp", headers=sse_headers, verify=False, stream=True)
        results["/mcp (SSE)"] = {
            "method": "GET",
            "status": res.status_code,
            "headers": dict(res.headers),
            "is_json": False,
            "body": "Connected to SSE stream. Keep-alive active.",
            "description": "MCP Streamable HTTP SSE connection for server-to-client notifications (requires `Accept: text/event-stream`)."
        }
        res.close()
        
    except Exception as e:
        print(f"Error during testing: {e}")
    finally:
        print("Stopping server...")
        server.stop_server()
        
    doc_path = Path("docs/https_wrapper_endpoints.md")
    print(f"Generating documentation at {doc_path}...")
    generate_markdown(doc_path, results)
    print("Done!")

if __name__ == "__main__":
    run_tests()
